//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BuiltInBars
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class DottedBar : IBar
	{
		public virtual void Resize(integer newHeight)
		{
			throw new System.NotImplementedException();
		}

		public virtual void SlideAdded(Slied slide)
		{
			throw new System.NotImplementedException();
		}

	}
}

